# Generated by Django 5.1 on 2024-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
    ]
