# Generated by Django 5.1 on 2024-09-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=64)),
            ],
        ),
    ]
